### ISSUE TITLE
Does discharge and death affect the number of cases?

### ISSUE THREAD

**Issue by zim96** [ynshung/covid-19-malaysia#10]
:question: 

I am trying to put in new columns that would track new cases in the last day and new cases in the past week. So, I would like to know if the number of cases is indeed the total number of confirmed cases. Ergo, the recoveries and deaths do not affect them

**Comment by ynshung** [comment]
No, the number of cases including the national, states and district level are all cumulative and will not be affected by recoveries & deaths. You can compare the cases for one day and the day before for the no. of case increased.

**Comment by zim96** [comment]
Alright, thanks for the clarification :)
