### ISSUE TITLE
District cases by states

### ISSUE THREAD

**Issue by lejarx** [ynshung/covid-19-malaysia#22]
Hi

Thanks for getting this repo set up and maintained.

I'm interested in the latest Covid cases by districts, I found an archive version here https://github.com/ynshung/covid-19-malaysia/tree/master/archive though they are not updated, is it because KKM stops sharing cases by districts?

**Comment by ynshung** [comment]
Hello, the district's cases are not updated because there's a few inconsistencies in the data on a few days (such as data not tallying with total national/states cases). Also it is really tedious to copy the data from an image manually day by day.

**Comment by lejarx** [comment]
@ynshung thanks for your reply. Any chances of getting the raw data (district cases) from KKM? If they can generate the images, they must have the data in csv/excel somewhere...

**Comment by ynshung** [comment]
Well, I have not any info on any raw data provided by KKM yet. Maybe you can try help searching for the data (non-image form) or request data from KKM directly.

**Comment by ynshung** [comment]
@lejarx You can watch out for [this official repo](https://github.com/MoH-Malaysia/covid19-public). It doesn't contain the district cases yet, but other users had requested for it so we can watch out for that.
