### ISSUE TITLE
Types of vaccine distribution by age

### ISSUE THREAD

**Issue by isivana38** [ynshung/covid-19-malaysia#29]
It is shown that Astra Zeneca vaccine performed superbly. Could it be the recipients are younger .

**Comment by isivana38** [comment]
Az was first offered to the above 60 and received huge uproars from this group. Hence the government decided to allow opt in for 18 and above. During the second round only 300,000 out of 1.2 miles doses was taken up by the above 60 even though they were given the priority to opt in one day earlier.

**Comment by ynshung** [comment]
Hello, please direct your requests on [this official repository](https://github.com/MoH-Malaysia/covid19-public). Thank you.
